### ISSUE TITLE
Motion Box gets a typescript error

### ISSUE THREAD

**Issue by bwcr** [sozonome/nextarter-chakra#149]
### Describe the bug

Running pnpm type-check returns this error:

```
> nextarter-chakra@0.1.0 type-check /home
> tsc --noEmit

src/lib/components/motion-box.tsx:6:33 - error TS2345: Argument of type 'ChakraComponent<"div", {}>' is not assignable to parameter of type 'string | ForwardRefExoticComponent<MergeWithAs<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any, Omit<ChakraProps, never>, As>>'.
  Property '$$typeof' is missing in type 'ChakraComponent<"div", {}>' but required in type 'ForwardRefExoticComponent<MergeWithAs<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any, Omit<ChakraProps, never>, As>>'.

6 export const MotionBox = motion(chakra.div);
                                  ~~~~~~~~~~

  node_modules/.pnpm/@types+react@18.3.5/node_modules/@types/react/index.d.ts:636:18
    636         readonly $$typeof: symbol;
                         ~~~~~~~~
    '$$typeof' is declared here.


Found 1 error in src/lib/components/motion-box.tsx:6

 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

Run `pnpm type-check`

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.41 GB / 11.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - /mnt/c/Program Files/nodejs/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.4.0 - /mnt/c/Program Files/nodejs/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bwcr** [comment]
I was unaware that it had been removed in the latest update. I can't find Motion Box anywhere in the repo

**Comment by sozonome** [comment]
Hi @bwcr , the latest version of the template is preparing for Chakra-UI v3 which will not depend on framer-motion anymore as peer deps.

If you project still need framer-motion kindly take a look at this resource for that: https://v2.chakra-ui.com/getting-started/with-framer

**Comment by bwcr** [comment]
> Hi @bwcr , the latest version of the template is preparing for Chakra-UI v3 which will not depend on framer-motion anymore as peer deps.
> 
> 
> 
> If you project still need framer-motion kindly take a look at this resource for that: https://v2.chakra-ui.com/getting-started/with-framer

Really appreciate the consideration for Chakra v3. I think I made the right choice to rely on your template! 😊
